language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install unittest2 flake8 --use-mirrors
  - python setup.py install
  - pip install coveralls
  - pip install requests_mock
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then flake8 onfido; fi
  - python -W always setup.py test
  - coverage run --source=onfido setup.py test
after_success:
  - coveralls